//
//Здесь содержится схема структуры данных,
//для буфера протоколов, с которой работает gRPC
//

//Синтаксис для буфера

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.16.0
// source: proto/BooksDB.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookid  uint32 `protobuf:"varint,1,opt,name=bookid,proto3" json:"bookid,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year    string `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	Edition string `protobuf:"bytes,4,opt,name=edition,proto3" json:"edition,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetBookid() uint32 {
	if x != nil {
		return x.Bookid
	}
	return 0
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Book) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorid  uint32 `protobuf:"varint,1,opt,name=authorid,proto3" json:"authorid,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{1}
}

func (x *Author) GetAuthorid() uint32 {
	if x != nil {
		return x.Authorid
	}
	return 0
}

func (x *Author) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Author) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type BookAuthor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookid   uint32 `protobuf:"varint,1,opt,name=bookid,proto3" json:"bookid,omitempty"`
	Authorid uint32 `protobuf:"varint,2,opt,name=authorid,proto3" json:"authorid,omitempty"`
}

func (x *BookAuthor) Reset() {
	*x = BookAuthor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAuthor) ProtoMessage() {}

func (x *BookAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAuthor.ProtoReflect.Descriptor instead.
func (*BookAuthor) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{2}
}

func (x *BookAuthor) GetBookid() uint32 {
	if x != nil {
		return x.Bookid
	}
	return 0
}

func (x *BookAuthor) GetAuthorid() uint32 {
	if x != nil {
		return x.Authorid
	}
	return 0
}

type CreateBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type CreateBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type ReadBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookid string `protobuf:"bytes,1,opt,name=bookid,proto3" json:"bookid,omitempty"`
}

func (x *ReadBookRequest) Reset() {
	*x = ReadBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookRequest) ProtoMessage() {}

func (x *ReadBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookRequest.ProtoReflect.Descriptor instead.
func (*ReadBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{5}
}

func (x *ReadBookRequest) GetBookid() string {
	if x != nil {
		return x.Bookid
	}
	return ""
}

type ReadBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *ReadBookResponse) Reset() {
	*x = ReadBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookResponse) ProtoMessage() {}

func (x *ReadBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookResponse.ProtoReflect.Descriptor instead.
func (*ReadBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{6}
}

func (x *ReadBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type ReadBooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadBooksRequest) Reset() {
	*x = ReadBooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBooksRequest) ProtoMessage() {}

func (x *ReadBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBooksRequest.ProtoReflect.Descriptor instead.
func (*ReadBooksRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{7}
}

type ReadBooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *ReadBooksResponse) Reset() {
	*x = ReadBooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBooksResponse) ProtoMessage() {}

func (x *ReadBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBooksResponse.ProtoReflect.Descriptor instead.
func (*ReadBooksResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{8}
}

func (x *ReadBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type UpdateBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type UpdateBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *UpdateBookResponse) Reset() {
	*x = UpdateBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookResponse) ProtoMessage() {}

func (x *UpdateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookid string `protobuf:"bytes,1,opt,name=bookid,proto3" json:"bookid,omitempty"`
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBookRequest) GetBookid() string {
	if x != nil {
		return x.Bookid
	}
	return ""
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAuthorRequest) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *CreateAuthorResponse) Reset() {
	*x = CreateAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorResponse) ProtoMessage() {}

func (x *CreateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{14}
}

func (x *CreateAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ReadAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorid string `protobuf:"bytes,1,opt,name=authorid,proto3" json:"authorid,omitempty"`
}

func (x *ReadAuthorRequest) Reset() {
	*x = ReadAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorRequest) ProtoMessage() {}

func (x *ReadAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorRequest.ProtoReflect.Descriptor instead.
func (*ReadAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{15}
}

func (x *ReadAuthorRequest) GetAuthorid() string {
	if x != nil {
		return x.Authorid
	}
	return ""
}

type ReadAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *ReadAuthorResponse) Reset() {
	*x = ReadAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorResponse) ProtoMessage() {}

func (x *ReadAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorResponse.ProtoReflect.Descriptor instead.
func (*ReadAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{16}
}

func (x *ReadAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ReadAuthorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadAuthorsRequest) Reset() {
	*x = ReadAuthorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorsRequest) ProtoMessage() {}

func (x *ReadAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ReadAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{17}
}

type ReadAuthorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authors []*Author `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
}

func (x *ReadAuthorsResponse) Reset() {
	*x = ReadAuthorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorsResponse) ProtoMessage() {}

func (x *ReadAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ReadAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{18}
}

func (x *ReadAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type UpdateAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *UpdateAuthorRequest) Reset() {
	*x = UpdateAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthorRequest) ProtoMessage() {}

func (x *UpdateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthorRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateAuthorRequest) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type UpdateAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *UpdateAuthorResponse) Reset() {
	*x = UpdateAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthorResponse) ProtoMessage() {}

func (x *UpdateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthorResponse.ProtoReflect.Descriptor instead.
func (*UpdateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type DeleteAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorid string `protobuf:"bytes,1,opt,name=authorid,proto3" json:"authorid,omitempty"`
}

func (x *DeleteAuthorRequest) Reset() {
	*x = DeleteAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorRequest) ProtoMessage() {}

func (x *DeleteAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorRequest.ProtoReflect.Descriptor instead.
func (*DeleteAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteAuthorRequest) GetAuthorid() string {
	if x != nil {
		return x.Authorid
	}
	return ""
}

type DeleteAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteAuthorResponse) Reset() {
	*x = DeleteAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorResponse) ProtoMessage() {}

func (x *DeleteAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorResponse.ProtoReflect.Descriptor instead.
func (*DeleteAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteAuthorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateBookAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookauthor *BookAuthor `protobuf:"bytes,1,opt,name=bookauthor,proto3" json:"bookauthor,omitempty"`
}

func (x *CreateBookAuthorRequest) Reset() {
	*x = CreateBookAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookAuthorRequest) ProtoMessage() {}

func (x *CreateBookAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateBookAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{23}
}

func (x *CreateBookAuthorRequest) GetBookauthor() *BookAuthor {
	if x != nil {
		return x.Bookauthor
	}
	return nil
}

type CreateBookAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookauthor *BookAuthor `protobuf:"bytes,1,opt,name=bookauthor,proto3" json:"bookauthor,omitempty"`
}

func (x *CreateBookAuthorResponse) Reset() {
	*x = CreateBookAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookAuthorResponse) ProtoMessage() {}

func (x *CreateBookAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateBookAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{24}
}

func (x *CreateBookAuthorResponse) GetBookauthor() *BookAuthor {
	if x != nil {
		return x.Bookauthor
	}
	return nil
}

type ReadBookAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookid   string `protobuf:"bytes,1,opt,name=bookid,proto3" json:"bookid,omitempty"`
	Authorid string `protobuf:"bytes,2,opt,name=authorid,proto3" json:"authorid,omitempty"`
}

func (x *ReadBookAuthorRequest) Reset() {
	*x = ReadBookAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookAuthorRequest) ProtoMessage() {}

func (x *ReadBookAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookAuthorRequest.ProtoReflect.Descriptor instead.
func (*ReadBookAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{25}
}

func (x *ReadBookAuthorRequest) GetBookid() string {
	if x != nil {
		return x.Bookid
	}
	return ""
}

func (x *ReadBookAuthorRequest) GetAuthorid() string {
	if x != nil {
		return x.Authorid
	}
	return ""
}

type ReadBookAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookauthor *BookAuthor `protobuf:"bytes,1,opt,name=bookauthor,proto3" json:"bookauthor,omitempty"`
}

func (x *ReadBookAuthorResponse) Reset() {
	*x = ReadBookAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookAuthorResponse) ProtoMessage() {}

func (x *ReadBookAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookAuthorResponse.ProtoReflect.Descriptor instead.
func (*ReadBookAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{26}
}

func (x *ReadBookAuthorResponse) GetBookauthor() *BookAuthor {
	if x != nil {
		return x.Bookauthor
	}
	return nil
}

type ReadBooksAuthorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadBooksAuthorsRequest) Reset() {
	*x = ReadBooksAuthorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBooksAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBooksAuthorsRequest) ProtoMessage() {}

func (x *ReadBooksAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBooksAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ReadBooksAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{27}
}

type ReadBooksAuthorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Booksauthors []*BookAuthor `protobuf:"bytes,1,rep,name=booksauthors,proto3" json:"booksauthors,omitempty"`
}

func (x *ReadBooksAuthorsResponse) Reset() {
	*x = ReadBooksAuthorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBooksAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBooksAuthorsResponse) ProtoMessage() {}

func (x *ReadBooksAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBooksAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ReadBooksAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{28}
}

func (x *ReadBooksAuthorsResponse) GetBooksauthors() []*BookAuthor {
	if x != nil {
		return x.Booksauthors
	}
	return nil
}

type UpdateBookAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookauthor *BookAuthor `protobuf:"bytes,1,opt,name=bookauthor,proto3" json:"bookauthor,omitempty"`
}

func (x *UpdateBookAuthorRequest) Reset() {
	*x = UpdateBookAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBookAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookAuthorRequest) ProtoMessage() {}

func (x *UpdateBookAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookAuthorRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateBookAuthorRequest) GetBookauthor() *BookAuthor {
	if x != nil {
		return x.Bookauthor
	}
	return nil
}

type UpdateBookAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookauthor *BookAuthor `protobuf:"bytes,1,opt,name=bookauthor,proto3" json:"bookauthor,omitempty"`
}

func (x *UpdateBookAuthorResponse) Reset() {
	*x = UpdateBookAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBookAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookAuthorResponse) ProtoMessage() {}

func (x *UpdateBookAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookAuthorResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateBookAuthorResponse) GetBookauthor() *BookAuthor {
	if x != nil {
		return x.Bookauthor
	}
	return nil
}

type DeleteBookAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookid   string `protobuf:"bytes,1,opt,name=bookid,proto3" json:"bookid,omitempty"`
	Authorid string `protobuf:"bytes,2,opt,name=authorid,proto3" json:"authorid,omitempty"`
}

func (x *DeleteBookAuthorRequest) Reset() {
	*x = DeleteBookAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookAuthorRequest) ProtoMessage() {}

func (x *DeleteBookAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookAuthorRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteBookAuthorRequest) GetBookid() string {
	if x != nil {
		return x.Bookid
	}
	return ""
}

func (x *DeleteBookAuthorRequest) GetAuthorid() string {
	if x != nil {
		return x.Authorid
	}
	return ""
}

type DeleteBookAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteBookAuthorResponse) Reset() {
	*x = DeleteBookAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookAuthorResponse) ProtoMessage() {}

func (x *DeleteBookAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookAuthorResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteBookAuthorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReadBookAuthorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *ReadBookAuthorsRequest) Reset() {
	*x = ReadBookAuthorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookAuthorsRequest) ProtoMessage() {}

func (x *ReadBookAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ReadBookAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{33}
}

func (x *ReadBookAuthorsRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type ReadBookAuthorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book    *Book     `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Authors []*Author `protobuf:"bytes,2,rep,name=authors,proto3" json:"authors,omitempty"`
}

func (x *ReadBookAuthorsResponse) Reset() {
	*x = ReadBookAuthorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookAuthorsResponse) ProtoMessage() {}

func (x *ReadBookAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ReadBookAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{34}
}

func (x *ReadBookAuthorsResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *ReadBookAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type ReadBooksAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *ReadBooksAuthorRequest) Reset() {
	*x = ReadBooksAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBooksAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBooksAuthorRequest) ProtoMessage() {}

func (x *ReadBooksAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBooksAuthorRequest.ProtoReflect.Descriptor instead.
func (*ReadBooksAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{35}
}

func (x *ReadBooksAuthorRequest) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ReadBooksAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author *Author `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Books  []*Book `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *ReadBooksAuthorResponse) Reset() {
	*x = ReadBooksAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_BooksDB_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBooksAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBooksAuthorResponse) ProtoMessage() {}

func (x *ReadBooksAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_BooksDB_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBooksAuthorResponse.ProtoReflect.Descriptor instead.
func (*ReadBooksAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_BooksDB_proto_rawDescGZIP(), []int{36}
}

func (x *ReadBooksAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *ReadBooksAuthorResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_proto_BooksDB_proto protoreflect.FileDescriptor

var file_proto_BooksDB_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x22, 0x60,
	0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x60, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x6f, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44,
	0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x37, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x29, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x64,
	0x22, 0x35, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x11, 0x52,
	0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22, 0x36, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x6f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73,
	0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x37, 0x0a,
	0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x2b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x3e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x44, 0x42, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x22, 0x3f, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x22, 0x2f, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x13, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x22, 0x3e, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x3f, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x31, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64,
	0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x4e, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a,
	0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x22, 0x4f, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x22, 0x4b, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64,
	0x22, 0x4d, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x6f,
	0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22,
	0x19, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x18, 0x52, 0x65,
	0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x0c, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x22,
	0x4e, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x6f,
	0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22,
	0x4f, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x62,
	0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x22, 0x4d, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64, 0x22,
	0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x3b, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f,
	0x6f, 0x6b, 0x22, 0x67, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b,
	0x12, 0x29, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x22, 0x41, 0x0a, 0x16, 0x52,
	0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x67,
	0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x44, 0x42, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x32, 0xdc, 0x0a, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x19,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1a,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x44, 0x42, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x44, 0x42, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44,
	0x42, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x49, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x1b,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x44, 0x42, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x44, 0x42, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73,
	0x44, 0x42, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x20, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x59, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x20, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73,
	0x44, 0x42, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x12, 0x20, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1f, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x12, 0x1f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x44, 0x42, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_BooksDB_proto_rawDescOnce sync.Once
	file_proto_BooksDB_proto_rawDescData = file_proto_BooksDB_proto_rawDesc
)

func file_proto_BooksDB_proto_rawDescGZIP() []byte {
	file_proto_BooksDB_proto_rawDescOnce.Do(func() {
		file_proto_BooksDB_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_BooksDB_proto_rawDescData)
	})
	return file_proto_BooksDB_proto_rawDescData
}

var file_proto_BooksDB_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_BooksDB_proto_goTypes = []interface{}{
	(*Book)(nil),                     // 0: BooksDB.Book
	(*Author)(nil),                   // 1: BooksDB.Author
	(*BookAuthor)(nil),               // 2: BooksDB.BookAuthor
	(*CreateBookRequest)(nil),        // 3: BooksDB.CreateBookRequest
	(*CreateBookResponse)(nil),       // 4: BooksDB.CreateBookResponse
	(*ReadBookRequest)(nil),          // 5: BooksDB.ReadBookRequest
	(*ReadBookResponse)(nil),         // 6: BooksDB.ReadBookResponse
	(*ReadBooksRequest)(nil),         // 7: BooksDB.ReadBooksRequest
	(*ReadBooksResponse)(nil),        // 8: BooksDB.ReadBooksResponse
	(*UpdateBookRequest)(nil),        // 9: BooksDB.UpdateBookRequest
	(*UpdateBookResponse)(nil),       // 10: BooksDB.UpdateBookResponse
	(*DeleteBookRequest)(nil),        // 11: BooksDB.DeleteBookRequest
	(*DeleteBookResponse)(nil),       // 12: BooksDB.DeleteBookResponse
	(*CreateAuthorRequest)(nil),      // 13: BooksDB.CreateAuthorRequest
	(*CreateAuthorResponse)(nil),     // 14: BooksDB.CreateAuthorResponse
	(*ReadAuthorRequest)(nil),        // 15: BooksDB.ReadAuthorRequest
	(*ReadAuthorResponse)(nil),       // 16: BooksDB.ReadAuthorResponse
	(*ReadAuthorsRequest)(nil),       // 17: BooksDB.ReadAuthorsRequest
	(*ReadAuthorsResponse)(nil),      // 18: BooksDB.ReadAuthorsResponse
	(*UpdateAuthorRequest)(nil),      // 19: BooksDB.UpdateAuthorRequest
	(*UpdateAuthorResponse)(nil),     // 20: BooksDB.UpdateAuthorResponse
	(*DeleteAuthorRequest)(nil),      // 21: BooksDB.DeleteAuthorRequest
	(*DeleteAuthorResponse)(nil),     // 22: BooksDB.DeleteAuthorResponse
	(*CreateBookAuthorRequest)(nil),  // 23: BooksDB.CreateBookAuthorRequest
	(*CreateBookAuthorResponse)(nil), // 24: BooksDB.CreateBookAuthorResponse
	(*ReadBookAuthorRequest)(nil),    // 25: BooksDB.ReadBookAuthorRequest
	(*ReadBookAuthorResponse)(nil),   // 26: BooksDB.ReadBookAuthorResponse
	(*ReadBooksAuthorsRequest)(nil),  // 27: BooksDB.ReadBooksAuthorsRequest
	(*ReadBooksAuthorsResponse)(nil), // 28: BooksDB.ReadBooksAuthorsResponse
	(*UpdateBookAuthorRequest)(nil),  // 29: BooksDB.UpdateBookAuthorRequest
	(*UpdateBookAuthorResponse)(nil), // 30: BooksDB.UpdateBookAuthorResponse
	(*DeleteBookAuthorRequest)(nil),  // 31: BooksDB.DeleteBookAuthorRequest
	(*DeleteBookAuthorResponse)(nil), // 32: BooksDB.DeleteBookAuthorResponse
	(*ReadBookAuthorsRequest)(nil),   // 33: BooksDB.ReadBookAuthorsRequest
	(*ReadBookAuthorsResponse)(nil),  // 34: BooksDB.ReadBookAuthorsResponse
	(*ReadBooksAuthorRequest)(nil),   // 35: BooksDB.ReadBooksAuthorRequest
	(*ReadBooksAuthorResponse)(nil),  // 36: BooksDB.ReadBooksAuthorResponse
}
var file_proto_BooksDB_proto_depIdxs = []int32{
	0,  // 0: BooksDB.CreateBookRequest.book:type_name -> BooksDB.Book
	0,  // 1: BooksDB.CreateBookResponse.book:type_name -> BooksDB.Book
	0,  // 2: BooksDB.ReadBookResponse.book:type_name -> BooksDB.Book
	0,  // 3: BooksDB.ReadBooksResponse.books:type_name -> BooksDB.Book
	0,  // 4: BooksDB.UpdateBookRequest.book:type_name -> BooksDB.Book
	0,  // 5: BooksDB.UpdateBookResponse.book:type_name -> BooksDB.Book
	1,  // 6: BooksDB.CreateAuthorRequest.author:type_name -> BooksDB.Author
	1,  // 7: BooksDB.CreateAuthorResponse.author:type_name -> BooksDB.Author
	1,  // 8: BooksDB.ReadAuthorResponse.author:type_name -> BooksDB.Author
	1,  // 9: BooksDB.ReadAuthorsResponse.authors:type_name -> BooksDB.Author
	1,  // 10: BooksDB.UpdateAuthorRequest.author:type_name -> BooksDB.Author
	1,  // 11: BooksDB.UpdateAuthorResponse.author:type_name -> BooksDB.Author
	2,  // 12: BooksDB.CreateBookAuthorRequest.bookauthor:type_name -> BooksDB.BookAuthor
	2,  // 13: BooksDB.CreateBookAuthorResponse.bookauthor:type_name -> BooksDB.BookAuthor
	2,  // 14: BooksDB.ReadBookAuthorResponse.bookauthor:type_name -> BooksDB.BookAuthor
	2,  // 15: BooksDB.ReadBooksAuthorsResponse.booksauthors:type_name -> BooksDB.BookAuthor
	2,  // 16: BooksDB.UpdateBookAuthorRequest.bookauthor:type_name -> BooksDB.BookAuthor
	2,  // 17: BooksDB.UpdateBookAuthorResponse.bookauthor:type_name -> BooksDB.BookAuthor
	0,  // 18: BooksDB.ReadBookAuthorsRequest.book:type_name -> BooksDB.Book
	0,  // 19: BooksDB.ReadBookAuthorsResponse.book:type_name -> BooksDB.Book
	1,  // 20: BooksDB.ReadBookAuthorsResponse.authors:type_name -> BooksDB.Author
	1,  // 21: BooksDB.ReadBooksAuthorRequest.author:type_name -> BooksDB.Author
	1,  // 22: BooksDB.ReadBooksAuthorResponse.author:type_name -> BooksDB.Author
	0,  // 23: BooksDB.ReadBooksAuthorResponse.books:type_name -> BooksDB.Book
	3,  // 24: BooksDB.BookService.CreateBook:input_type -> BooksDB.CreateBookRequest
	5,  // 25: BooksDB.BookService.GetBook:input_type -> BooksDB.ReadBookRequest
	7,  // 26: BooksDB.BookService.GetBooks:input_type -> BooksDB.ReadBooksRequest
	9,  // 27: BooksDB.BookService.UpdateBook:input_type -> BooksDB.UpdateBookRequest
	11, // 28: BooksDB.BookService.DeleteBook:input_type -> BooksDB.DeleteBookRequest
	13, // 29: BooksDB.BookService.CreateAuthor:input_type -> BooksDB.CreateAuthorRequest
	15, // 30: BooksDB.BookService.GetAuthor:input_type -> BooksDB.ReadAuthorRequest
	17, // 31: BooksDB.BookService.GetAuthors:input_type -> BooksDB.ReadAuthorsRequest
	19, // 32: BooksDB.BookService.UpdateAuthor:input_type -> BooksDB.UpdateAuthorRequest
	21, // 33: BooksDB.BookService.DeleteAuthor:input_type -> BooksDB.DeleteAuthorRequest
	23, // 34: BooksDB.BookService.CreateBookAuthor:input_type -> BooksDB.CreateBookAuthorRequest
	25, // 35: BooksDB.BookService.GetBookAuthor:input_type -> BooksDB.ReadBookAuthorRequest
	27, // 36: BooksDB.BookService.GetBooksAuthors:input_type -> BooksDB.ReadBooksAuthorsRequest
	29, // 37: BooksDB.BookService.UpdateBookAuthor:input_type -> BooksDB.UpdateBookAuthorRequest
	31, // 38: BooksDB.BookService.DeleteBookAuthor:input_type -> BooksDB.DeleteBookAuthorRequest
	33, // 39: BooksDB.BookService.GetAuthorsBook:input_type -> BooksDB.ReadBookAuthorsRequest
	35, // 40: BooksDB.BookService.GetAuthorBooks:input_type -> BooksDB.ReadBooksAuthorRequest
	4,  // 41: BooksDB.BookService.CreateBook:output_type -> BooksDB.CreateBookResponse
	6,  // 42: BooksDB.BookService.GetBook:output_type -> BooksDB.ReadBookResponse
	8,  // 43: BooksDB.BookService.GetBooks:output_type -> BooksDB.ReadBooksResponse
	10, // 44: BooksDB.BookService.UpdateBook:output_type -> BooksDB.UpdateBookResponse
	12, // 45: BooksDB.BookService.DeleteBook:output_type -> BooksDB.DeleteBookResponse
	14, // 46: BooksDB.BookService.CreateAuthor:output_type -> BooksDB.CreateAuthorResponse
	16, // 47: BooksDB.BookService.GetAuthor:output_type -> BooksDB.ReadAuthorResponse
	18, // 48: BooksDB.BookService.GetAuthors:output_type -> BooksDB.ReadAuthorsResponse
	20, // 49: BooksDB.BookService.UpdateAuthor:output_type -> BooksDB.UpdateAuthorResponse
	22, // 50: BooksDB.BookService.DeleteAuthor:output_type -> BooksDB.DeleteAuthorResponse
	24, // 51: BooksDB.BookService.CreateBookAuthor:output_type -> BooksDB.CreateBookAuthorResponse
	26, // 52: BooksDB.BookService.GetBookAuthor:output_type -> BooksDB.ReadBookAuthorResponse
	28, // 53: BooksDB.BookService.GetBooksAuthors:output_type -> BooksDB.ReadBooksAuthorsResponse
	30, // 54: BooksDB.BookService.UpdateBookAuthor:output_type -> BooksDB.UpdateBookAuthorResponse
	32, // 55: BooksDB.BookService.DeleteBookAuthor:output_type -> BooksDB.DeleteBookAuthorResponse
	34, // 56: BooksDB.BookService.GetAuthorsBook:output_type -> BooksDB.ReadBookAuthorsResponse
	36, // 57: BooksDB.BookService.GetAuthorBooks:output_type -> BooksDB.ReadBooksAuthorResponse
	41, // [41:58] is the sub-list for method output_type
	24, // [24:41] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_BooksDB_proto_init() }
func file_proto_BooksDB_proto_init() {
	if File_proto_BooksDB_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_BooksDB_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookAuthor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAuthorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAuthorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBooksAuthorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBooksAuthorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBookAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBookAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookAuthorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookAuthorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBooksAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_BooksDB_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBooksAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_BooksDB_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_BooksDB_proto_goTypes,
		DependencyIndexes: file_proto_BooksDB_proto_depIdxs,
		MessageInfos:      file_proto_BooksDB_proto_msgTypes,
	}.Build()
	File_proto_BooksDB_proto = out.File
	file_proto_BooksDB_proto_rawDesc = nil
	file_proto_BooksDB_proto_goTypes = nil
	file_proto_BooksDB_proto_depIdxs = nil
}
